### PR TITLE
checksum character can be an X as well as a 0-9

### PR DESCRIPTION
**Pull request by jspaaks**
fixes issue #1

### CODE REVIEW

**Comment by sdruskat** [comment]
@jspaaks Thanks for the PR and sorry for sitting on it for so long!

**Comment by jspaaks** [comment]
No worries, I understand you guys are busy. It's just that in the past I got burned a couple times with PRs that never got merged (not in this github organization just to be clear), so these days I try to get some idea of my chances before I get invested.

**Comment by sdruskat** [comment]
@jspaaks Absolutely understandable. I'd love to onboard more people that can merge PRs. I'd be happy to add you as an Admin to the `schema` project if you're happy to be one? We can always discuss changes either of us is unsure about before merging...

**Comment by sdruskat** [comment]
Fix #1

**Pull request merged**
