### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ots22**

### CODE REVIEW

**Review by sdruskat — APPROVED** [review]
I tend to cut out the "How to apply" bit at the end (think it's a flaw of the Apache license text website), then again it's the only place where it appears if you don't have license headers in the individual files. Of course there's the option to add headers to files, which would be great to have, but I really don't wanna put this on you (unless you want to of course).

**Comment by ots22** [comment]
Following our discussion, should we scratch this and go with CC-BY instead?

**Comment by jspaaks** [comment]
(Cue Sponge Bob's "One eternity later"...)

Hi Oliver, first off, thanks for the PR. I think this now no longer necessary since we are continuing development of the schema and the spec in one repo https://github.com/citation-file-format/citation-file-format, which is indeed licensed under CC-BY as you suggested.

**Comment by sdruskat** [comment]
Yes, thanks @ots22 for your PR, and sorry for sitting on this for ages!

**Pull request closed without merging**
